before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended
script:
- mkdir _build
- latexmk -pdf -outdir=_build lab01/cs100S2020_lab01.tex
- latexmk -pdf -outdir=_build lab02/cs100S2020_lab02.tex
- latexmk -pdf -outdir=_build lab03/cs100S2020_lab03.tex
- latexmk -pdf -outdir=_build lab04/cs100S2020_lab04.tex
- latexmk -pdf -outdir=_build lab05/cs100S2020_lab05.tex
- latexmk -pdf -outdir=_build lab06/cs100S2020_lab06.tex
- latexmk -pdf -outdir=_build lab07/cs100S2020_lab07.tex
- latexmk -pdf -outdir=_build practical01/cs100S2020_practical01.tex
- latexmk -pdf -outdir=_build practical02/cs100S2020_practical02.tex
- latexmk -pdf -outdir=_build practical03/cs100S2020_practical03.tex
- latexmk -pdf -outdir=_build practical04/cs100S2020_practical04.tex
- latexmk -pdf -outdir=_build practical05/cs100S2020_practical05.tex
- latexmk -pdf -outdir=_build practical06/cs100S2020_practical06.tex
- latexmk -pdf -outdir=_build practical07/cs100S2020_practical07.tex
- latexmk -pdf -outdir=_build quiz01/cs100S2020_studyguide_quiz01.tex
- latexmk -pdf -outdir=_build exam01/cs100S2020_studyguide_exam01.tex
deploy:
  provider: releases
  api_key:
    secure: BNxUrKPw7crGTFdFBK9Ot462UK8zPaqitgrIk7EiIfw1uf7ni/U6lt1eKuETbJ3t5BN+2klpcWtfHnD1zT9jOvG38u6UE6vVRVYVV1Kjb+xzbmlU899Ni/UW2lElVr/N6b3706JD6NKx3JH0asZzAZo8wmORNCi3QmTLWyBFy6YdyyCvXOUJlAScjtAS9+KrKFBTNy0jtydePt+MYZusdaNw4mbhZUVxVzpCuzo6SWENv7q7iPbNoA6LHGxwuSyKw0Ac5wEADPZj5n0wpnL6KvaGBnVdhd86QbJqR/WPDGV4t3sNabDBa1Rc+C+OHPZL6P+vKcogZV5DqJIoJX/KZvrfxRI2Ebw9QrnyiLnXxC+tSKQtKA6oPYSRDxyTu0ih163G28LOV/7Bce5LB9Vjr8K2DqDl5Q7G8dyvBsFwdHUHY+ebNpVH1l3X2oavtQT1kr+dVGQaUma7oo1K9Hnd1apQ+iqO6SSato6xflFBdlTz354DT47DjcsCR9MLMnaaswMGxCB+WjfFElL+nqkWLaGVWK2J2vjQSwD4WabihC3D9Db/fmk7IFvfcUQXTbq98VEoUFueX2gOYhwGaJbH37A7gms+BO+UhhzBWYVkixINrCosrpEnFn3NwG+pv4ETIFF/mz+J0h1WS/d84/AR7d63BSIXvijV7PngyksJP7w=
  file:
    - _build/cs100S2020_lab01.pdf
    - _build/cs100S2020_lab02.pdf
    - _build/cs100S2020_lab03.pdf
    - _build/cs100S2020_lab04.pdf
    - _build/cs100S2020_lab05.pdf
    - _build/cs100S2020_lab06.pdf
    - _build/cs100S2020_lab07.pdf
    - _build/cs100S2020_practical01.pdf
    - _build/cs100S2020_practical02.pdf
    - _build/cs100S2020_practical03.pdf
    - _build/cs100S2020_practical04.pdf
    - _build/cs100S2020_practical05.pdf
    - _build/cs100S2020_practical06.pdf
    - _build/cs100S2020_practical07.pdf
    - _build/cs100S2020_studyguide_quiz01.pdf
    - _build/cs100S2020_studyguide_exam01.pdf
  skip_cleanup: true
  on:
    tags: true
